services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./gateway/.env
    environment:
      - FINANCE_SERVICE_URL=http://financeservice:8000
      - RATIO_SERVICE_URL=http://ratioservice:8003
      - ESG_SERVICE_URL=http://esgservice:8002
      - STOCK_SERVICE_URL=http://stockservice:8001
      - GATEWAY_SERVICE_URL=http://gateway:8080
    volumes:
      - ./gateway:/app
    networks:
      - lif-network
    depends_on:
      - financeservice
      - ratioservice
      - esgservice
      - stockservice
    
  financeservice:
    build:
      context: ./financeservice
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./financeservice/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/lifdb
      - GATEWAY_SERVICE_URL=http://gateway:8080
    volumes:
      - ./financeservice:/app
    networks:
      - lif-network
    depends_on:
      - postgres

  ratioservice:
    build:
      context: ./ratioservice
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - ./ratioservice/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/lifdb
      - GATEWAY_SERVICE_URL=http://gateway:8080
    volumes:
      - ./ratioservice:/app
    networks:
      - lif-network
    depends_on:
      - postgres
    
  esgservice:
    build:
      context: ./esgservice
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./esgservice/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/lifdb
      - GATEWAY_SERVICE_URL=http://gateway:8080
    volumes:
      - ./esgservice:/app
    networks:
      - lif-network
    depends_on:
      - postgres
    
  stockservice:
    build:
      context: ./stockservice
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./stockservice/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/lifdb
      - GATEWAY_SERVICE_URL=http://gateway:8080
    volumes:
      - ./stockservice:/app
    networks:
      - lif-network
    depends_on:
      - postgres
    
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lifdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lif-network

networks:
  lif-network:
    driver: bridge

volumes:
  postgres_data: 